{% set name = "mdformat-deflist" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_deflist-{{ version }}.tar.gz
  sha256: 3bcb156831aa6a021db5f4d165544173355f02f5dbdf35d1a097fc1704289f51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=1.0.0
    - mdit-py-plugins >=0.2.7

test:
  imports:
    - mdformat_deflist
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/executablebooks/mdformat-deflist
  summary: An mdformat plugin for markdown-it-deflist.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
