{% set name = "mdformat-deflist" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdformat_deflist-{{ version }}.tar.gz
  sha256: 7b4bd183507c37dcff7bffaf8e442d7b69e4d90fb94558fe95b3ece68ec94cf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - mdformat >=0.7.0,<0.8.0
    - mdit-py-plugins >=0.2.7,<0.4.0

test:
  imports:
    - mdformat_deflist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/mdformat-deflist
  summary: An mdformat plugin for markdown-it-deflist.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
