{% set name = "mdformat-deflist" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_deflist-{{ version }}.tar.gz
  sha256: b25091ce1705a37c0cc87ddb1c78a3e7eb43d50adcdb5ad4763411f743ae6f7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=0.7.0,<0.8.0
    - mdit-py-plugins >=0.2.7,<0.4.0

test:
  imports:
    - mdformat_deflist
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/executablebooks/mdformat-deflist
  summary: An mdformat plugin for markdown-it-deflist.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
